name: magic_300
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.41
  video_player: ^2.9.1
  provider: ^6.1.2
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/splash.png
    - assets/images/zone_background.png
    - assets/images/sparkle.png
    - assets/images/rainbow.png
    - assets/images/bubble.png
    - assets/audio/Spell_Sound.m4a
    - assets/videos/video1.mp4
    - assets/videos/video2.mp4
    - assets/videos/video3.mp4
    - assets/videos/video4.mp4
    - assets/videos/video5.mp4
    - assets/videos/video6.mp4
    - assets/videos/video7.mp4
    - assets/videos/video8.mp4
    - assets/videos/video9.mp4
    - assets/videos/video10.mp4
    - assets/videos/video11.mp4
    - assets/videos/video12.mp4
    - assets/videos/video13.mp4
    - assets/videos/video14.mp4
    - assets/videos/video15.mp4
    - assets/videos/video16.mp4
    - assets/videos/video17.mp4
    - assets/videos/video18.mp4
    - assets/videos/video19.mp4
    - assets/videos/video20.mp4
    - assets/videos/video21.mp4
    - assets/videos/video22.mp4
    - assets/videos/video23.mp4
    - assets/videos/video24.mp4
    


  